# This docker-compose is for developer convenience, not for running in production.

services:

  postgres:  # for hive
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepassword
      POSTGRES_DB: hive

  minio:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopassword
    ports:
      - 9000:9000
      - 9001:9001
    command: 'server /data --console-address ":9001"'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1s
      retries: 5

  minio-create-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_URL: http://minio:9000
      MINIO_USER: miniouser
      MINIO_PWD: miniopassword
      MINIO_IMPORTER_USER: importers
      MINIO_IMPORTER_PWD: impassword
      MINIO_IMPORTER_RAW_BUCKET: cts-output
      MINIO_IMPORTER_SQL_BUCKET: cdm-lake
      MINIO_SQL_WAREHOUSE_PATH: users-sql-warehouse
    entrypoint: /s3_policies/minio_create_bucket_entrypoint.sh
    volumes:
      - ./s3_policies:/s3_policies

  hive-metastore:
    image: ghcr.io/berdatalakehouse/hive_metastore:0.0.1
    platform: linux/amd64
    ports:
      - "9083:9083"
    environment:
      POSTGRES_DB: hive
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepassword
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: miniouser
      S3_SECRET_KEY: miniopassword
      DELTALAKE_WAREHOUSE_DIR: s3a://cdm-lake/users-sql-warehouse
    depends_on:
      postgres:
        condition: service_started
      minio-create-bucket:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9083"]
      interval: 30s
      timeout: 10s
      retries: 3

  spark-master:
    image: ghcr.io/berdatalakehouse/kube_spark_manager_image:pr-7
    platform: linux/amd64
    ports:
      - 8090:8090
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8090
      MAX_EXECUTORS: 4
      EXECUTOR_CORES: 2
      MAX_CORES_PER_APPLICATION: 10

  spark-worker-1:
    image: ghcr.io/berdatalakehouse/kube_spark_manager_image:pr-7
    platform: linux/amd64
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_PORT: 8083
      SPARK_WORKER_WEBUI_PORT: 8081
      # these don't seem to be used
      BERDL_REDIS_HOST: "fake"
      BERDL_REDIS_PORT: 10000
      BERDL_HIVE_METASTORE_URI: fake
      BERDL_DELTALAKE_WAREHOUSE_DIRECTORY_PATH: fake

  spark-worker-2:
    image: ghcr.io/berdatalakehouse/kube_spark_manager_image:pr-7
    platform: linux/amd64
    depends_on:
      - spark-master
    ports:
      - 8082:8082
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_PORT: 8084
      SPARK_WORKER_WEBUI_PORT: 8082
      # these don't seem to be used
      BERDL_REDIS_HOST: "fake"
      BERDL_REDIS_PORT: 10000
      BERDL_HIVE_METASTORE_URI: fake
      BERDL_DELTALAKE_WAREHOUSE_DIRECTORY_PATH: fake

  # A test image for testing purposes. The importers repo is built into the event processor,
  # and so does not have an independent image.
  test-container:  # do not use underscore or spark will barf
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_started
      spark-worker-1:
        condition: service_started
      spark-worker-2:
        condition: service_started
      minio-create-bucket:
        condition: service_completed_successfully
    environment:
      # test variables used by the test helper code
      IMP_MINIO_URL: http://minio:9000
      IMP_MINIO_ACCESS_KEY: importers
      IMP_MINIO_SECRET_KEY: impassword
      IMP_SPARK_MASTER_URL: spark://spark-master:7077
      IMP_SPARK_DRIVER_HOST: test-container
      IMP_HIVE_METASTORE_URI: thrift://hive-metastore:9083
      IMP_MINIO_IMPORTER_RAW_BUCKET: cts-output
      IMP_SQL_WAREHOUSE_PREFIX: s3a://cdm-lake/users-sql-warehouse/

      # By default the mounted code directory is not writeable by spark_user. As such,
      # when running tests with coverage:
      # 1) Create a coverage dir in the repo root and make it world writeable.
      # 2) Instruct pytest to write coverage files there,
      #    e.g. --cov-report xml:./coverage/coverage.xml 
      COVERAGE_FILE: /imp_test/coverage/.coverage
    volumes:
      - ./:/imp_test
