name: KBase CDM Task Service tests

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    # run workflow when merging to main or develop
    branches:
      - main
      - master
      - develop

jobs:

  task_service_tests:
    runs-on: ubuntu-22.04

    steps:
    
    - name: Repo checkout
      uses: actions/checkout@v4
    
    - name: Run tests
      shell: bash
      run: |
        # make the coverage directory world writeable, otherwise spark_user can't write to it
        mkdir coverage
        chmod a+w coverage

        docker compose up -d --build
        docker compose exec test-container pytest test -vv --cov=cdmeventimporters --cov-report xml:./coverage/coverage.xml
        docker compose down

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
